## NumPy: [Library]

### Arrays:

In [1]:
my_list = [1,3,5,7,9,11]
my_list

[1, 3, 5, 7, 9, 11]

In [43]:
import numpy as np
import sys

In [10]:
# casting above list into np. array...
arr = np.array(my_list)
print(f"arr: {arr}")
print(f"size: {sys.getsizeof(arr)} bytes")

arr: [ 1  3  5  7  9 11]
size: 136 bytes


In [45]:
# we can also define the datatype along with declaration of an array to avoid the extra memory usage...
arr = np.array(my_list, dtype=np.int8)
print(f"arr: {arr}")
print(f"size: {sys.getsizeof(arr)} bytes")

arr: [ 1  3  5  7  9 11]
size: 118 bytes


In [44]:
# Will insert junk values if we try to insert value that is not valid...
np.array([1,3,543456521, 4.5], np.int8)

C:\Users\kyghe\AppData\Local\Temp\ipykernel_7652\1508853750.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 543456521 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  np.array([1,3,543456521, 4.5], np.int8)


array([1, 3, 9, 4], dtype=int8)

In [42]:
# Multi-dimensional array...

my_matrix = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Common Ways to create NumPy arrays:

1. Creating array of specific range:

- `np.arange(start, end, step=1)`

In [26]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2. Creating array of all zeros:


In [27]:
np.zeros(3)

array([0., 0., 0.])

In [29]:
# n-dimensional of zeros:
np.zeros( (3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

3. Creating array of ones:

In [32]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

4. Creating linearly-spaced arrays in given range:

In [33]:
# np.linspace(start, stop, even_space=50)

np.linspace(0,10, 8)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

5. Identity Matrix (size -> n * n):

In [34]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

6. Arrays of Random Numbers:

In [53]:
# random numbers in uniform distribution...(range: 0-1)
np.random.rand(5)

array([0.99487016, 0.67484201, 0.44863117, 0.13721633, 0.43337689])

In [55]:
# random numbers in standard normal distribution
np.random.randn(3)

array([ 0.65210091, -2.04838003, -0.28917634])

In [62]:
np.random.randint(0,10)

6

7. Creating Empty Array:

In [64]:
np.empty((2,3))

array([[ 1.,  3.,  5.],
       [ 7.,  9., 11.]])

---

### More Array methods & attributes:

In [70]:
arr = np.arange(0,25)
ran_arr = np.random.randint(0,25, 27)

print(f"""arr: {arr}
ran_arr: {ran_arr}""")

arr: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
ran_arr: [15 21  6  0 23  0  4 18  7  4  9 21 21 18  8 21 14 18 15 16  7  6  0  2
  8 13 19]


1. Reshaping array (1d->2d):

In [71]:
arr_2d = arr.reshape(5,5)
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [73]:
arr_3d = ran_arr.reshape(3,3,3)
arr_3d

array([[[15, 21,  6],
        [ 0, 23,  0],
        [ 4, 18,  7]],

       [[ 4,  9, 21],
        [21, 18,  8],
        [21, 14, 18]],

       [[15, 16,  7],
        [ 6,  0,  2],
        [ 8, 13, 19]]])

In [78]:
arr_2d.reshape(arr_2d.size)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [83]:
# n-D array to 1-D array using .ravel() method.

arr_3d.ravel()

array([15, 21,  6,  0, 23,  0,  4, 18,  7,  4,  9, 21, 21, 18,  8, 21, 14,
       18, 15, 16,  7,  6,  0,  2,  8, 13, 19])

In [82]:
arrRavel

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

2. Min/Max values method:

In [88]:
print(f"Minimum value: {ran_arr.min()}")
print(f"Maximum value: {ran_arr.max()}")

Minimum value: 0
Maximum value: 23


3. Sorting an array:

In [92]:
sor_arr = np.array([54,32,43,23,5,32])
sor_arr.sort()
sor_arr

array([ 5, 23, 32, 32, 43, 54])

In [94]:
# .argsort() - will give the indices of the array to be sorted...
sor_arr = np.array([54,32,43,23,5,32])
sor_arr.argsort()

array([4, 3, 1, 5, 2, 0], dtype=int64)

In [ ]:
# .argsort() in 2-D array using axis:

two = np.array([
    [1,2,3],
    [4,2,4],
    [3,7,8]
])

two.argsort(axis=0) # vertically...

array([[0, 0, 0],
       [2, 1, 1],
       [1, 2, 2]], dtype=int64)

In [97]:
two = np.array([
    [1,2,3],
    [4,2,4],
    [3,7,8]
])

two.argsort(axis=1) # horizontally...

array([[0, 1, 2],
       [1, 0, 2],
       [0, 1, 2]], dtype=int64)

5. Finding the shape of arr:

In [98]:
arr.shape

(6,)

In [99]:
two.shape

(3, 3)

6. Finding Data Type:

In [100]:
two.dtype

dtype('int32')

In [101]:
np.array([1,3,4,5], dtype=np.int8).dtype


dtype('int8')

### NumPy Indexing & Selection:

In [103]:
arr = np.arange(0,11)
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [106]:
# We can use same indexing and slicing method as that of the python list.
print(arr[10])
print(arr[1:])
print(arr[5:9:2])

10
[ 1  2  3  4  5  6  7  8  9 10]
[5 7]


In [107]:
arr_2d = np.array([
    [5,10,15],
    [20,25,30],
    [35,40,45]
])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [109]:
print(arr_2d[2][2])
print(arr_2d[1,2])

45
30


### Conditional Selection Method:

In [110]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [112]:
arr > 5 

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [113]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

### Finding element in arr:

In [114]:
arr2d = np.random.randint(0,100, (3,5))
arr2d

array([[25, 75, 90,  2, 60],
       [11, 26,  4, 10, 31],
       [57, 80, 73, 83,  3]])

In [117]:
np.where(arr2d == 4) # returns tuple of array positions

(array([1], dtype=int64), array([2], dtype=int64))

### NumPy Operations:

-> Same as matrix operations:

In [118]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [119]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [120]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [121]:
arr * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [122]:
arr / 0

C:\Users\kyghe\AppData\Local\Temp\ipykernel_7652\3942562399.py:1: RuntimeWarning: divide by zero encountered in divide
  arr / 0
C:\Users\kyghe\AppData\Local\Temp\ipykernel_7652\3942562399.py:1: RuntimeWarning: invalid value encountered in divide
  arr / 0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [123]:
arr / arr 

C:\Users\kyghe\AppData\Local\Temp\ipykernel_7652\2663351161.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [124]:
# Square root:

np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [125]:
# Exponential:

np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [126]:
# Finding the logs of every element:

np.log(arr)

C:\Users\kyghe\AppData\Local\Temp\ipykernel_7652\1745042186.py:3: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [127]:
# Finding Sum:

np.sum(arr)

55

In [128]:
# Finding Std. Deviation:

np.std(arr) # or arr.std()

3.1622776601683795

In [129]:
arr2d

array([[25, 75, 90,  2, 60],
       [11, 26,  4, 10, 31],
       [57, 80, 73, 83,  3]])

In [130]:
np.sum(arr2d, axis=0)

array([ 93, 181, 167,  95,  94])

In [131]:
np.sum(arr2d, axis=1)

array([252,  82, 296])

In [134]:
# Transpose of Matrix:

arr2d.T

array([[25, 11, 57],
       [75, 26, 80],
       [90,  4, 73],
       [ 2, 10, 83],
       [60, 31,  3]])

### Fetching iterator using .flat attribute:

In [137]:
for item in arr.flat:
    print(item)

0
1
2
3
4
5
6
7
8
9
10


### Extras (NumPy):


In [139]:
arr.nbytes

44

In [140]:
arr2d.ndim

2

In [ ]:
# Finding Non-zero elements:

arr_nz= np.array([1,2,4,0,3,0,4,0,5]).reshape(3,3)
print(np.count_nonzero(arr_nz))
print(np.nonzero(arr_nz)) #represents the dimensions...

6
(array([0, 0, 0, 1, 2, 2], dtype=int64), array([0, 1, 2, 1, 0, 2], dtype=int64))


In [143]:
arr_nz

array([[1, 2, 4],
       [0, 3, 0],
       [4, 0, 5]])

In [144]:
# to list:

arr.tolist()

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]